### PR TITLE
Merge adapta for Adapta theme

### PR DESCRIPTION
**Pull request by RedFantom**
Hey all!

This branch contains a theme derived from the Adapta theme. It is birght and relatively low-contrast. As the Adapta theme is usually paired with a modern font such as Roboto, this branch also includes support for [TkinterEP/python-tkextrafont](https://github.com/TkinterEP/python-tkextrafont), which allows loading external non-system font files into Tkinter.

This is what the theme looks like with the Roboto font loaded:
adapta

On the topic of including fonts with the themes, I would like some feedback. Personally I like the idea, but if anyone has any thoughts to share, I'd appreciate it.

If not, then I'll merge it like this. Of course, the fonts will only be loaded if you install `python-tkextrafont` explicitly. It's not on PyPI yet. Install it using
```
python -m pip install git+https://github.com/TkinterEP/python-tkextrafont
```

### CODE REVIEW

**Comment by RedFantom** [comment]
This PR is pending as I want to change it so it uses [`fonttools`](https://github.com/fonttools/fonttools) instead.

**Comment by Akuli** [comment]
Getting new dependencies for ttkthemes feels a bit odd to me, because ttkthemes used to be just a bunch of Tcl files and a small amount of Python code to load them. However, if new themes look much nicer with better fonts than operating systems provide, then including fonts with themes is a good idea IMO.

**Comment by RedFantom** [comment]
@Akuli Well, personally I would like to extend the capabilities further to get the most out of Tkinter. Currently I am considering putting more advanced functionality in a separate package instead so as not to complicate this package. In case you have an opinion on whether it should be a different package or this one may grow larger, I'd really like to get your input.

**Comment by RedFantom** [comment]
This branch has now been rebased onto master, and only the theme is included in the changes. Font support has been removed from this package, at least for now.

I have had very little time to spend on developing an alternative method of loading themes that allows for easy and proper loading of font files, and including `tkextrafont` at this point without additional testing seems irresponsible to me.

**Pull request merged**
